name: pre-commit

on:
    push:
        branches:
            - "**"
    pull_request:
        branches: ["main"]

jobs:
    pre-commit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python
              uses: actions/setup-python@v3
            - name: Autoflake8 linting
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install autoflake8
                  autoflake8 --in-place --expand-star-imports --remove-duplicate-keys --remove-unused-variables -v -v  ./recsyslearn/*/*.py
