name: pre-commit

on:
    push:
        branches:
            - "**"
    pull_request:
        branches: [ "main" ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.0
      with:
        extra_args: autoflake8 --in-place --expand-star-imports --remove-duplicate-keys --remove-unused-variables -v -v *.py